version: "3.8"
services:
  mysqldb:
    image: mysql:5.7.8
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - dbVolume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  backend:
    image: onsbha/achat:1.2.0
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
  front:
    image: onsbha/achat.front:1.2.0
    restart: unless-stopped
    ports:
      - 80:80
volumes:
  dbVolume:

