version: "3.8"
services:
  mydb:
    image: mysql:5.7.8
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - dbVolume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
  backend:
    image: balkiss7/achat:11
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mydb
  frontend:
    image: balkiss7/operateur-front:1.0
    restart: unless-stopped
    ports:
      - 80:80
volumes:
  dbVolume: