version: '3.8'

networks:
  my_network:   # Define a custom network
    driver: bridge

  backendNetwork:  # Define another custom network
    driver: bridge

  frontendNetwork:  # Define yet another custom network
    driver: bridge

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: achatdb
    volumes:
      - db:/var/lib/msql
    networks:
      - backendNetwork

  achat-backend:
    image: samarcherni/achat:1.5
    restart: unless-stopped
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    networks:
      - backendNetwork
      - frontendNetwork
  achat-frontend:
    image: samarcherni/bekindfront:1.11
    restart: unless-stopped
    ports:
      - 4200:80
    volumes:
      - frontend-data:/usr/share/nginx/html
    networks:
      - frontendNetwork

volumes:
  db:
  frontend-data:
